[package]
name = "os-rust"
version = "0.1.0"
edition = "2024"
authors = ["Song Khoi   <songkhoi123@gmail.com>"]

[dependencies]
bootloader = "0.9.29"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
